version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: app:v1.0.0
        container_name: paket-santri-app
        restart: unless-stopped
        volumes:
            - laravel_storage:/app/storage
            - laravel_cache:/app/bootstrap/cache
        ports:
            - "9001:90"

volumes:
    laravel_storage:
    laravel_cache:
